import { useEffect, useState } from 'react'
import { ArrowDownToLine, ArrowUpRight, Code2, Download, ExternalLink, GraduationCap, Mail, MapPin, Menu, Phone, X } from 'lucide-react'
import { portfolioData as me, projects, skills } from './data/portfolioData'

const external = { target: '_blank', rel: 'noopener noreferrer' }
const nav = [['Home', '#home'], ['About', '#about'], ['Skills', '#skills'], ['Projects', '#projects'], ['Experience', '#experience'], ['Education', '#education'], ['Contact', '#contact']]

function SectionTitle({ number, eyebrow, title, children }) { return <div className="section-heading"><p className="eyebrow"><span>{number}</span> / {eyebrow}</p><h2>{title}</h2>{children}</div> }

function Navbar() {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false)
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 18); onScroll(); addEventListener('scroll', onScroll); return () => removeEventListener('scroll', onScroll) }, [])
  return <header className={'nav-wrap ' + (scrolled ? 'is-scrolled' : '')}><nav className="nav container" aria-label="Main navigation"><a className="brand" href="#home" aria-label="Home">RM<span>.</span></a><div className="nav-links">{nav.slice(0, 5).map(([n, h]) => <a href={h} key={n}>{n}</a>)}<a href={me.cv} {...external}>CV</a></div><a className="nav-github" href={me.github} {...external}>GitHub <ArrowUpRight size={15}/></a><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu" aria-expanded={open}>{open ? <X/> : <Menu/>}</button></nav>{open && <div className="mobile-menu">{nav.map(([n,h]) => <a href={h} onClick={() => setOpen(false)} key={n}>{n}</a>)}<a href={me.cv} {...external}>View CV</a><a href={me.github} {...external}>GitHub <ArrowUpRight size={15}/></a><a href={me.linkedin} {...external}>LinkedIn <ArrowUpRight size={15}/></a></div>}</header>
}

function Hero() { const [imageError, setImageError] = useState(false); return <section id="home" className="hero container"><div className="portrait-side reveal"><div className="portrait-ring">{imageError ? <div className="portrait-fallback" aria-label="Profile photo placeholder">RM</div> : <img src={me.profileImage} alt="Rugandura Maurice" onError={() => setImageError(true)} />}</div><div className="portrait-note"><span><MapPin size={15}/> Rwanda</span><strong>Software Engineering<br/>Student</strong><small>Available for: <em>Internships · Projects · Collaboration</em></small></div></div><div className="hero-copy reveal"><p className="hello">Hi, I’m</p><h1>RUGANDURA<br/><span>MAURICE</span></h1><p className="role">Software Engineering Student<br/>&amp; Developer</p><p className="intro">I am a Software Engineering student focused on building practical software solutions while developing my skills in web development, cybersecurity, networking, and information technology.</p><div className="hero-actions"><a className="button primary" href="#projects">View Projects <ArrowDownToLine size={17}/></a><a className="button secondary" href={me.cv} {...external}>View CV <ExternalLink size={16}/></a></div><div className="social-row"><a href={me.github} {...external}><Code2 size={19}/> GitHub <ArrowUpRight size={15}/></a><a href={me.linkedin} {...external}><Code2 size={19}/> LinkedIn <ArrowUpRight size={15}/></a></div></div></section> }

function About() { return <section id="about" className="section container two-col"><SectionTitle number="01" eyebrow="ABOUT" title="About Me"/><div className="prose"><p>I am a Software Engineering student at the Adventist University of Central Africa (AUCA), with practical exposure to ICT support, computer troubleshooting, system configuration, networking, software development, and software security.</p><p>My academic studies and practical experience have allowed me to work with different technologies while developing my ability to analyze problems and build practical solutions.</p><p>I am particularly interested in software engineering, web development, cybersecurity, networking, and systems.</p></div></section> }

function Skills() { return <section id="skills" className="section section-muted"><div className="container"><SectionTitle number="02" eyebrow="SKILLS" title="Technical Skills"/><div className="skills-grid">{skills.map(([title, tags]) => <article className="skill-card" key={title}><Code2 size={21}/><h3>{title}</h3><div>{tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div></article>)}</div></div></section> }

function Projects() { return <section id="projects" className="section container"><SectionTitle number="03" eyebrow="PROJECTS" title="Selected Projects"/><div className="project-grid">{projects.map(project => <article className="project-card" key={project.title}><div className="project-top"><span className="featured">Featured project</span><Code2 size={21}/></div><h3>{project.title}</h3><div className="project-tags">{project.technologies.map(t => <span className="tag" key={t}>{t}</span>)}</div><p>{project.description}</p><a className="text-link" href={project.github} {...external}>View on GitHub <ArrowUpRight size={17}/></a></article>)}</div></section> }

function Experience() { const responsibilities = ['Assisted employees with computer hardware and software problems.', 'Installed and configured Windows operating systems.', 'Troubleshot software-related issues and configured printers and peripherals.', 'Assisted with network cable installation and security camera troubleshooting.', 'Learned about server infrastructure and the server-room environment.', 'Gained exposure to computer and software security.']; return <section id="experience" className="section section-muted"><div className="container"><SectionTitle number="04" eyebrow="EXPERIENCE" title="Practical Experience"/><article className="experience-card"><div className="timeline-dot"/><div className="experience-head"><div><p className="date">06 JUL 2026 — 04 SEP 2026</p><h3>Kabuye Sugar Works <span>(K.S.W Ltd)</span></h3><p className="position">ICT Trainee / Industrial Attachment</p></div><p className="place"><MapPin size={16}/> Rwanda</p></div><p className="experience-summary">Gained practical experience within the ICT department through computer support, system configuration, networking activities, troubleshooting, and technical assistance.</p><ul>{responsibilities.map(item => <li key={item}>{item}</li>)}</ul></article></div></section> }

function Education() { return <section id="education" className="section container"><SectionTitle number="05" eyebrow="EDUCATION" title="Education"/><article className="education-card"><GraduationCap/><div><p className="date">2024 — PRESENT · RWANDA</p><h3>Adventist University of Central Africa <span>(AUCA)</span></h3><p>Bachelor’s Degree in Software Engineering</p></div></article></section> }

function CVSection() { return <section className="section"><div className="container cv-panel"><div><p className="eyebrow"><span>06</span> / CURRICULUM VITAE</p><h2>Want to know more<br/>about my background?</h2><p>View my one-page CV for a concise overview of my education, experience, skills, and projects.</p></div><div className="cv-actions"><a className="button primary" href={me.cv} {...external}>View CV <ExternalLink size={16}/></a><a className="button secondary" href={me.cv} download="Rugandura-Maurice-CV.pdf">Download CV <Download size={16}/></a></div></div></section> }

function Contact() { return <section id="contact" className="section section-muted"><div className="container"><SectionTitle number="07" eyebrow="CONTACT" title="Let’s Connect"><p className="heading-copy">I’m always interested in learning, building, and connecting with people in technology.</p></SectionTitle><div className="contact-grid"><a href={'mailto:' + me.email}><Mail/><span><small>EMAIL</small>{me.email}</span><ArrowUpRight/></a><a href={'tel:' + me.phone}><Phone/><span><small>PHONE</small>{me.phone}</span></a><a href={me.github} {...external}><Code2/><span><small>GITHUB</small>github.com/mauricerugandura</span><ArrowUpRight/></a><a href={me.linkedin} {...external}><Code2/><span><small>LINKEDIN</small>linkedin.com/in/rugandura-maurice-974284384</span><ArrowUpRight/></a></div></div></section> }

function Footer() { return <footer><div className="container footer-inner"><div><a className="brand" href="#home">RM<span>.</span></a><p>Software Engineering Student &amp; Developer</p></div><div className="footer-links"><a href={me.github} {...external}>GitHub</a><a href={me.linkedin} {...external}>LinkedIn</a><a href={'mailto:' + me.email}>Email</a></div><p>© 2026 Rugandura Maurice</p></div></footer> }
export default function App() { return <><Navbar/><main><Hero/><About/><Skills/><Projects/><Experience/><Education/><CVSection/><Contact/></main><Footer/></> }
